import AppShell from "../components/AppShell";
import {Badge, Button, Card, Progress, SectionTitle, Stat} from "../components/UI";
import type {Role} from "../types";

type Ctx={title:string;subtitle:string;role:Role;kind:string};

const data={
 student:{skills:[["React.js",92],["Node.js",88],["Problem Solving",85],["Communication",78],["MongoDB",76],["Python",54],["System Design",38]], jobs:[["Software Engineer","Google","₹25 LPA","92% match"],["SDE Intern","Microsoft","₹1.2 L/pm","88% match"],["Backend Developer","Amazon","₹18 LPA","84% match"]]},
 recruiter:{candidates:[["Aarav Mehta","78","React · Node · SQL","Shortlisted"],["Priya Shah","84","Python · AWS · SQL","Interview"],["Rohan Patil","71","Java · Spring · DBMS","Review"]]},
 tpo:{students:[["Aarav Mehta","78","Placement Ready"],["Priya Shah","84","Placement Ready"],["Rohan Patil","56","Needs Improvement"],["Isha Kulkarni","42","At Risk"]]}
};

function StudentDashboard(){return <AppShell title="Overview" subtitle="Good evening, Aarav. Here's what needs your attention today."><div className="grid two"><Card className="readiness"><span className="eyebrow">PLACEMENT READINESS</span><div className="big-number">71 <small>/100</small></div><Badge tone="green">On track</Badge><Progress value={71}/><small className="green">↑ 5 points this month</small></Card><Card className="action-card"><span className="eyebrow">NEXT BEST ACTION</span><h2>Complete your DSA assessment</h2><p>15 questions · around 20 minutes</p><Button variant="secondary">Start assessment →</Button></Card></div><div className="grid four"><Stat label="Assessments" value="12" meta="8 passed"/><Stat label="Skill mastery" value="71%" meta="+6% this week" tone="green"/><Stat label="Interview readiness" value="68%" meta="Communication" tone="orange"/><Stat label="Applications" value="4" meta="2 active"/></div><div className="grid two lower"><Card><SectionTitle title="Skill mastery" sub="Where you're strong and where to focus next." action={<Button variant="secondary">View skill map →</Button>}/>{data.student.skills.slice(0,5).map(([s,v])=><div className="skill-row" key={s as string}><div><span>{s}</span><b>{v}%</b></div><Progress value={v as number}/></div>)}</Card><Card><SectionTitle title="Today's plan" sub="Small steps, measurable progress."/>{[["DSA practice","2 medium problems","20 min"],["Aptitude drill","15 quantitative questions","15 min"],["Interview practice","Tell me about yourself","10 min"]].map((x,i)=><div className="plan-row" key={i}><span className="step">{i+1}</span><div><b>{x[0]}</b><small>{x[1]}</small></div><em>{x[2]}</em></div>)}</Card></div></AppShell>}

function SkillMap(){return <AppShell title="Skill Map" subtitle="Track your skills, identify gaps, and get personalized recommendations."><div className="grid four"><Stat label="Total Skills" value="24" meta="↑ 6 this month"/><Stat label="Proficient" value="16" meta="67% of total" tone="green"/><Stat label="In Progress" value="6" meta="25% of total"/><Stat label="Needs Attention" value="2" meta="8% of total" tone="orange"/></div><div className="grid skill-layout"><Card><SectionTitle title="Your Skill Distribution" sub="A visual breakdown of your current skill levels."/><div className="donut-wrap"><div className="donut"><strong>24</strong><span>Skills</span></div><div className="legend"><p><i className="green-dot"/>Proficient <b>16 (67%)</b></p><p><i className="blue-dot"/>In Progress <b>6 (25%)</b></p><p><i className="orange-dot"/>Needs Attention <b>2 (8%)</b></p></div></div></Card><Card><SectionTitle title="Top Strengths" action={<Button variant="secondary">View all</Button>}/>{data.student.skills.slice(0,5).map(([s,v],i)=><div className="rank-row" key={s as string}><span className="rank">{i+1}</span><b>{s}</b><Progress value={v as number}/><small>{v}%</small></div>)}</Card></div><Card><SectionTitle title="All Skills" sub="Detailed view of your skills and progress."/><div className="table">{data.student.skills.map(([s,v])=><div className="table-row" key={s as string}><b>{s}</b><Badge tone={(v as number)>70?"green":"orange"}>{v as number>70?"Proficient":"Needs Attention"}</Badge><Progress value={v as number}/><span>{v}%</span><Button variant="secondary">View Details</Button></div>)}</div></Card></AppShell>}

function Assessments(){const items=[["DSA Assessment","Technical · 15 questions · 20 min","Recommended"],["Aptitude Assessment","Quantitative · 20 questions · 25 min","Ready"],["Communication Skills","Voice based · 10 min","Needs practice"],["Web Development","20 questions · 30 min","Ready"],["Database & SQL","15 questions · 20 min","Completed"]];return <AppShell title="Assessments" subtitle="Practice and evaluate with AI-powered assessments."><div className="filter-row"><Badge>All</Badge><Badge tone="gray">Technical</Badge><Badge tone="gray">Aptitude</Badge><Badge tone="gray">Communication</Badge><Badge tone="gray">Domain</Badge></div><Card>{items.map((x,i)=><div className="assessment-row" key={i}><div className="app-icon">{i+1}</div><div><b>{x[0]}</b><small>{x[1]}</small></div><Badge tone={x[2]==="Completed"?"green":x[2]==="Needs practice"?"orange":"purple"}>{x[2]}</Badge><Button>{x[2]==="Completed"?"Review":"Start"}</Button></div>)}</Card></AppShell>}

function Readiness(){return <AppShell title="Placement Readiness" subtitle="A transparent view of the signals contributing to your score."><div className="grid two"><Card className="center-score"><span className="eyebrow">Overall score</span><div className="score">78</div><small>/100</small><span className="green">↑ 5 points this month</span></Card><Card><SectionTitle title="Score breakdown"/>{[["Technical skills",84,"purple"],["Aptitude",76,"purple"],["Communication",68,"orange"],["Interview readiness",73,"purple"],["Resume strength",81,"green"]].map(x=><div className="metric-row" key={x[0]}><b>{x[0]}</b><Progress value={x[1] as number} tone={x[2] as string}/><strong>{x[1]}</strong></div>)}</Card></div><Card><SectionTitle title="What changed?"/><p>DSA assessment increased technical mastery by 4 points.</p><p>Two missed communication practices reduced the communication component by 1 point.</p><p className="muted">The score is recalculated from verified assessment and profile signals.</p></Card><div className="grid three"><Card><span className="eyebrow">Priority gap</span><h3>Communication</h3><p>Practice 10 min today</p></Card><Card><span className="eyebrow green">Recommended</span><h3>Mock interview</h3><p>Technical + HR</p></Card><Card><span className="eyebrow">Next review</span><h3>In 7 days</h3><p>After new evidence</p></Card></div></AppShell>}

function DailyPlan(){return <AppShell title="Daily Plan" subtitle="Personalized tasks to improve placement readiness."><Card><SectionTitle title="Today, 18 Sep 2026" sub="Small steps, measurable progress." action={<Badge tone="green">3 of 5 done</Badge>}/>{[["Solve 2 medium DSA problems","Arrays & Hashing","20 min"],["Practice 15 aptitude questions","Quantitative Ability","15 min"],["Communication practice","Record 3 answers","10 min"],["Update your resume","Add latest project","15 min"],["Review SQL concepts","Joins and indexing","20 min"]].map((x,i)=><div className="task-row" key={i}><input type="checkbox" defaultChecked={i<3}/><div><b>{x[0]}</b><small>{x[1]}</small></div><span>{x[2]}</span><Button variant="secondary">Start</Button></div>)}</Card><Card><SectionTitle title="Weekly goal"/><Progress value={60}/><p>3 / 5 days completed</p></Card></AppShell>}

function Resume(){return <AppShell title="Resume Analyzer" subtitle="Get AI-powered feedback to improve your resume."><div className="grid two"><Card className="upload"><SectionTitle title="Upload your resume" sub="PDF only · Max 5MB"/><div className="dropzone"><div>▤</div><b>Drop PDF here</b><small>or</small><Button>Upload resume</Button></div></Card><Card><SectionTitle title="Why analyze?"/>{["Get detailed AI feedback","Improve your resume score","Find missing keywords","Compare with target roles","Check ATS compatibility"].map(x=><p key={x}>✓ &nbsp;{x}</p>)}</Card></div><Card><SectionTitle title="Recent analysis"/><div className="analysis-row"><b>Aarav_Mehta_resume.pdf</b><Badge tone="green">78/100</Badge><Button>View feedback</Button></div></Card></AppShell>}

function Interview(){return <AppShell title="AI Mock Interview" subtitle="Practice with AI and get detailed feedback."><div className="filter-row"><Badge>Technical</Badge><Badge tone="gray">HR</Badge><Badge tone="gray">Behavioral</Badge><Badge tone="gray">Custom</Badge></div><div className="grid two"><Card className="interview-start"><div className="ai-orb">AI</div><h2>Start your AI mock interview</h2><p>Choose a target role for realistic questions.</p><Button>Start interview →</Button></Card><Card><SectionTitle title="Recent interviews"/>{[["Technical Round","DSA fundamentals","74/100"],["HR Round","Behavioral","79/100"],["Soft Skills","Communication","68/100"]].map(x=><div className="analysis-row" key={x[0]}><div><b>{x[0]}</b><small>{x[1]}</small></div><Badge tone="green">{x[2]}</Badge></div>)}</Card></div></AppShell>}

function Jobs(){return <AppShell title="Job Opportunities" subtitle="Discover and apply to companies hiring from your campus."><Card><div className="search wide">⌕ <span>Search companies, roles, or skills...</span></div>{data.student.jobs.map(x=><div className="job-row" key={x[0]}><div className="company-logo">G</div><div><b>{x[0]}</b><small>{x[1]} · {x[2]}</small></div><Badge tone="green">{x[3]}</Badge><Button>Apply</Button><Button variant="secondary">Save</Button></div>)}</Card></AppShell>}

function JobDetails(){return <AppShell title="Job Details" subtitle="Review role requirements and your fit."><Card className="job-hero"><div><span className="eyebrow">GOOGLE</span><h2>Software Engineer</h2><p>Bengaluru · Full-time · ₹25 LPA</p></div><Badge tone="green">92% match</Badge><Button>Apply now</Button></Card><div className="grid two"><Card><SectionTitle title="Job description"/><p>Build scalable systems and user experiences with a high-performing engineering team.</p><SectionTitle title="Requirements"/>{["B.E./B.Tech in IT, CS or related","Strong problem solving skills","Data structures & algorithms","React / Node.js","Good communication skills"].map(x=><p key={x}>• {x}</p>)}</Card><Card><SectionTitle title="Key dates"/>{[["Application deadline","30 Sep 2026"],["Test date","10 Oct 2026"],["Interview","20 Oct 2026"],["Location","Bengaluru, India"]].map(x=><div className="key-row" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</Card></div></AppShell>}

function Applications(){return <AppShell title="My Applications" subtitle="Track the status of your job applications."><div className="filter-row"><Badge>All (4)</Badge><Badge tone="gray">In Progress (3)</Badge><Badge tone="gray">Shortlisted (1)</Badge><Badge tone="gray">Rejected (0)</Badge></div><Card>{data.student.jobs.concat([["Full Stack Developer","Chetanai","₹12 LPA","79% match"]]).map((x,i)=><div className="job-row" key={x[0]}><div className="company-logo">{x[1].slice(0,1)}</div><div><b>{x[0]}</b><small>{x[1]} · Applied on {12-i} Sep 2026</small></div><Badge tone={i===0?"green":"purple"}>{i===0?"Shortlisted":"In Progress"}</Badge><Button variant="secondary">View</Button></div>)}</Card></AppShell>}

function Recruiter({page="dashboard"}:{page?:string}){if(page==="candidate")return <AppShell role="RECRUITER" title="Candidate Intelligence" subtitle="Evidence-based candidate profile and readiness."><Card className="candidate-head"><div className="avatar large">A</div><div><h2>Aarav Mehta</h2><p>B.E. Information Technology · VIT Pune</p></div><Button>Shortlist</Button><Button variant="secondary">Reject</Button></Card><div className="grid four"><Stat label="Placement readiness" value="78/100"/><Stat label="Technical" value="84"/><Stat label="Aptitude" value="76"/><Stat label="Communication" value="68" tone="orange"/></div><Card><SectionTitle title="Candidate overview"/>{[["Skills","React · Node.js · Python · SQL · MongoDB"],["Projects","QuickChat · Drive Rental · Agentic Agile"],["Assessment","DSA 84 · DBMS 82 · Aptitude 76"],["Interview","Technical 73 · HR 79 · Communication 68"],["Resume","78/100 · ATS compatible"]].map(x=><div className="key-row" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</Card></AppShell>;
 if(page==="jobs")return <AppShell role="RECRUITER" title="Create Job" subtitle="Create a structured opening for verified campus talent."><Card><div className="form-grid">{[["Job title","Software Engineer"],["Department","Engineering"],["Location","Bengaluru"],["Employment type","Full-time"],["CTC","₹12–25 LPA"],["Application deadline","30 Sep 2026"]].map(x=><label key={x[0]}>{x[0]}<input value={x[1]} readOnly/></label>)}</div><label>Job description<textarea value="Build scalable products with a strong engineering team." readOnly/></label><Button>Publish job</Button></Card></AppShell>;
 return <AppShell role="RECRUITER" title="Recruiter Dashboard" subtitle="Your candidate intelligence at a glance."><div className="grid four"><Stat label="Candidates" value="1,248" meta="+12%"/><Stat label="Active jobs" value="12" meta="3 new"/><Stat label="Shortlisted" value="86" meta="+8%"/><Stat label="Interviews" value="24" meta="This week"/></div><Card><SectionTitle title="Candidate pipeline" action={<Button>Find candidates</Button>}/>{data.recruiter.candidates.map(x=><div className="candidate-row" key={x[0]}><div className="avatar">{x[0][0]}</div><div><b>{x[0]}</b><small>{x[2]}</small></div><strong>{x[1]}/100</strong><Badge tone="green">{x[3]}</Badge><Button variant="secondary">View</Button></div>)}</Card></AppShell>}

function TPO({page="dashboard"}:{page?:string}){if(page==="students")return <AppShell role="TPO" title="Student Management" subtitle="Manage profiles, readiness and placement eligibility."><Card><SectionTitle title="Students" action={<Button>Import students</Button>}/><div className="table">{data.tpo.students.map(x=><div className="table-row" key={x[0]}><b>{x[0]}</b><span>{x[1]}/100</span><Badge tone={x[2]==="At Risk"?"orange":"green"}>{x[2]}</Badge><Button variant="secondary">View</Button></div>)}</div></Card></AppShell>;
 if(page==="drive")return <AppShell role="TPO" title="Create Placement Drive" subtitle="Configure eligibility, rounds and participating companies."><Card><div className="form-grid">{[["Drive name","Campus Hiring 2026"],["Company","Google"],["Role","Software Engineer"],["Package","₹25 LPA"],["Drive date","20 Oct 2026"],["Application deadline","30 Sep 2026"]].map(x=><label key={x[0]}>{x[0]}<input value={x[1]} readOnly/></label>)}</div><SectionTitle title="Eligibility rules"/><div className="grid four"><Stat label="Minimum CGPA" value="7.0"/><Stat label="Max backlogs" value="0"/><Stat label="Eligible branch" value="IT / CS"/><Stat label="Graduation" value="2027"/></div><Button>Create drive</Button></Card></AppShell>;
 return <AppShell role="TPO" title="Placement Intelligence" subtitle="Track student readiness, skill gaps and placement outcomes."><div className="grid four"><Stat label="Total Students" value="1,248" meta="Active"/><Stat label="Placement Ready" value="642" meta="51.4%" tone="green"/><Stat label="Needs Improvement" value="391" meta="31.3%" tone="orange"/><Stat label="Placed" value="215" meta="17.2%" tone="green"/></div><div className="grid two"><Card><SectionTitle title="Readiness distribution"/>{[["0–40",8],["41–60",17],["61–70",23],["71–80",31],["81–100",21]].map(x=><div className="bar-row" key={x[0]}><span>{x[0]}</span><Progress value={x[1] as number}/><b>{x[1]}%</b></div>)}</Card><Card><SectionTitle title="Priority skill gaps"/>{[["Communication",68],["System Design",54],["DSA",49],["Aptitude",43]].map(x=><div className="skill-row" key={x[0]}><div><span>{x[0]}</span><b>{x[1]}%</b></div><Progress value={x[1] as number} tone="orange"/></div>)}</Card></div><Card><SectionTitle title="Recent placement activity"/>{data.tpo.students.map(x=><div className="candidate-row" key={x[0]}><div className="avatar">{x[0][0]}</div><div><b>{x[0]}</b><small>Readiness score</small></div><strong>{x[1]}/100</strong><Badge tone={x[2]==="At Risk"?"orange":"green"}>{x[2]}</Badge><Button variant="secondary">View</Button></div>)}</Card></AppShell>}

function Profile(){return <AppShell title="Profile" subtitle="Keep your placement profile complete and verified."><Card><SectionTitle title="Personal information" action={<Button>Edit profile</Button>}/><div className="profile-grid"><div className="avatar huge">A</div><div><h2>Aarav Mehta</h2><p>aarav@student.edu</p><p>+91 98765 43210 · Nashik, Maharashtra</p></div></div></Card><div className="grid two"><Card><SectionTitle title="Education"/><p><b>B.E. Information Technology</b></p><p>International Institute of Information Technology</p><p>CGPA 8.43 · 2027</p></Card><Card><SectionTitle title="Skills"/><div className="tag-wrap">{["React","Node.js","MongoDB","Python","SQL","DSA","Git","AWS"].map(x=><Badge tone="gray" key={x}>{x}</Badge>)}</div></Card></div></AppShell>}

function Generic({ctx}:{ctx:Ctx}){return <AppShell role={ctx.role} title={ctx.title} subtitle={ctx.subtitle}><div className="grid four"><Stat label="Status" value="Active" meta="Updated today"/><Stat label="Progress" value="72%" meta="+8% this week" tone="green"/><Stat label="Items" value="24" meta="12 completed"/><Stat label="Next action" value="3" meta="Due today" tone="orange"/></div><Card><SectionTitle title="{0}" sub="Manage this part of your TalentBridge workspace with clear, structured actions." action={<Button>Create new</Button>}/><div className="placeholder-list">{["Overview and summary","Recent activity","Recommendations","History and status"].map((x,i)=><div key={x}><span className="app-icon">{i+1}</span><div><b>{x}</b><small>Detailed information and actions will appear here.</small></div><Badge tone={i===3?"green":"purple"}>{i===3?"Complete":"Active"}</Badge><Button variant="secondary">View</Button></div>)}</div></Card></AppShell>}

export default function PlatformPage({kind}:{kind:string}){
 const role:Role=kind.startsWith("recruiter")?"RECRUITER":kind.startsWith("tpo")?"TPO":"STUDENT";
 if(kind==="student-dashboard")return <StudentDashboard/>; if(kind==="skill-map")return <SkillMap/>; if(kind==="assessments")return <Assessments/>; if(kind==="readiness")return <Readiness/>; if(kind==="daily-plan")return <DailyPlan/>; if(kind==="resume")return <Resume/>; if(kind==="interview")return <Interview/>; if(kind==="jobs")return <Jobs/>; if(kind==="job-details")return <JobDetails/>; if(kind==="applications")return <Applications/>; if(kind==="profile")return <Profile/>; if(kind==="recruiter-dashboard")return <Recruiter/>; if(kind==="recruiter-candidate")return <Recruiter page="candidate"/>; if(kind==="recruiter-create-job")return <Recruiter page="jobs"/>; if(kind==="tpo-dashboard")return <TPO/>; if(kind==="tpo-students")return <TPO page="students"/>; if(kind==="tpo-drive")return <TPO page="drive"/>;
 const [title,subtitle]=kind.split("|"); return <Generic ctx={{kind,title,subtitle,role}}/>;
}
